name: PR CI
on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_SKIP_PROVIDER_REGISTRATION: true
  AZURE_WEBAPP_NAME: todos-api
  PROJECT_PATH: src/RestApi/RestApi.csproj
  PACKAGE_PATH: ./build
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}/react-webapp
  DOTNET_VERSION: '6.0.x'
  ARTIFACT_NAME: webapp
  DEV_SLOT_NAME: dev
  STG_SLOT_NAME: staging

jobs:
  terraform:
    name: Terraform
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: Azure Login 🔐
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.9

      - name: Terraform Init
        run:  terraform init -upgrade

      - name: Terraform Plan🔧
        run: terraform plan

      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Azure Logout 🔐
        run: az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      
      - name: Setup dotnet ${{ env.DOTNET_VERSION }}
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
            include-prerelease: true

      - name: Install dependencies 🔧
        run: dotnet restore

      - name: Build 🔧
        run: dotnet build

      - name: Test with the dotnet CLI ❌⚠✅
        run: dotnet test